# Generated by Django 2.2.6 on 2021-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ تغییر')),
                ('percent_of_the_first_author', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
