# Generated by Django 2.2.6 on 2021-05-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regulations',
        ),
    ]
