# Generated by Django 2.2.6 on 2021-05-09 08:35

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_regulations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ تغییر')),
                ('type_of_regulations', models.CharField(choices=[('promotional', 'ترفیع'), ('grant', 'پژوهانه یا گرنت'), ('right_to_encouragement', 'حق التشویق')], default='promotional', max_length=200, verbose_name='نوع آیین نامه')),
                ('percent_of_the_first_author', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, validators=[accounts.validators.validate_size], verbose_name='سهم یک نفر')),
                ('percent_of_the_second_author', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, validators=[accounts.validators.validate_size], verbose_name='سهم دونفر')),
                ('percent_of_the_third_author', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, validators=[accounts.validators.validate_size], verbose_name='سهم سه نفر')),
                ('percent_of_the_fourth_author', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, validators=[accounts.validators.validate_size], verbose_name='سهم چهار نفر')),
                ('percent_of_the_5th_author', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, validators=[accounts.validators.validate_size], verbose_name='سهم پنج نفر')),
                ('percent_of_the_6th_author', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, validators=[accounts.validators.validate_size], verbose_name='سهم شش نفر')),
                ('percent_article_abstract', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, validators=[accounts.validators.validate_size], verbose_name='درصد چکیده بودن مقاله')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
