# Generated by Django 2.2.6 on 2021-05-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210509_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulations',
            name='is_writer_responsible',
            field=models.CharField(choices=[('1', 'بله'), ('0', 'خیر')], default='1', max_length=1, verbose_name='نویسنده مسئول'),
        ),
    ]
