# Generated by Django 2.2.6 on 2021-05-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_regulations_is_writer_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='type_of_regulations',
            field=models.CharField(choices=[('absorption', 'جذب'), ('promotional', 'ترفیع'), ('grant', 'پژوهانه یا گرنت'), ('right_to_encouragement', 'حق التشویق'), ('status_conversion', 'تبدیل وضعیت')], default='absorption', max_length=200, verbose_name='نوع آیین نامه'),
        ),
    ]
