# Generated by Django 2.2.6 on 2021-05-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='score_first_quarter',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='امتیاز چارک اول'),
        ),
        migrations.AlterField(
            model_name='share',
            name='score_fourth_quarter',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='امتیاز چارک چهارم'),
        ),
        migrations.AlterField(
            model_name='share',
            name='score_second_quarter',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='امتیاز چارک دوم'),
        ),
        migrations.AlterField(
            model_name='share',
            name='score_third_quarter',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='امتیاز چارک سوم'),
        ),
    ]
